In [1]:
import pandas as pd

In [6]:
def process_csv(input_file, output_file):
    # Đọc tệp CSV
    df = pd.read_csv(input_file)
    
    # Giữ nguyên các dòng có nhãn BENIGN, MSSQL, LDAP, SYN
    labels_to_keep = ["BENIGN", "MSSQL", "LDAP", "Syn"]
    df_filtered = df[df['Label'].isin(labels_to_keep)]
    
    # Xử lý NetBIOS và Portmap (50% mỗi loại)
    netbios = df[df['Label'] == 'NetBIOS'].sample(frac=0.5, random_state=42)
    portmap = df[df['Label'] == 'Portmap'].sample(frac=0.5, random_state=42)
    netbios_portmap_merged = pd.concat([netbios, portmap])
    netbios_portmap_merged['Label'] = 'NetBIOS-Portmap'
    
    # Xử lý UDP và UDP-Lag (50% mỗi loại)
    udp = df[df['Label'] == 'UDP'].sample(frac=0.5, random_state=42)
    udp_lag = df[df['Label'] == 'UDPLag'].sample(frac=0.5, random_state=42)
    udp_merged = pd.concat([udp, udp_lag])
    udp_merged['Label'] = 'UDP-Combined'
    
    # Gộp tất cả lại
    final_df = pd.concat([df_filtered, netbios_portmap_merged, udp_merged])
    
    # Lưu ra tệp CSV mới
    final_df.to_csv(output_file, index=False)
    print(f"Tạo tệp {output_file} thành công!")

# Gọi hàm xử lý
process_csv('data/csv/cicddos_2019.csv', 'data/csv/cicddos_2019_6_labels.csv')

Tạo tệp data/csv/cicddos_2019_6_labels.csv thành công!

In [7]:
df = pd.read_csv('data/csv/cicddos_2019_6_labels.csv')
df['Label'].value_counts()

Label
BENIGN             5000
LDAP               5000
MSSQL              5000
Syn                5000
NetBIOS-Portmap    5000
UDP-Combined       5000
Name: count, dtype: int64

In [8]:
selected_columns = ['Protocol', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 
                    'Fwd Packets Length Total', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 
                    'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 
                    'Bwd Packet Length Mean', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 
                    'Flow IAT Max', 'Flow IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Min', 
                    'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 
                    'Bwd Header Length', 'Bwd Packets/s', 'Packet Length Max', 'FIN Flag Count', 'SYN Flag Count', 
                    'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 
                    'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 
                    'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Init Fwd Win Bytes', 'Init Bwd Win Bytes', 
                    'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Std', 'Label']

In [10]:
df = pd.read_csv('data/csv/cicddos_2019_6_labels.csv')
df = df[df['Label'] == 'Syn']
df = df[selected_columns]

In [19]:
df.sample(10)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,...,Bwd Avg Bulk Rate,Init Fwd Win Bytes,Init Bwd Win Bytes,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Std,Label
17690,6,1,2,0,12.0,6.0,6.0,0.0,0.0,0.0,...,0,5840,-1,20,0.0,0.000000,0.0,0.0,0.000000e+00,Syn
17796,6,45,2,0,12.0,6.0,6.0,0.0,0.0,0.0,...,0,5840,-1,20,0.0,0.000000,0.0,0.0,0.000000e+00,Syn
19344,6,2,2,0,12.0,6.0,6.0,0.0,0.0,0.0,...,0,5840,-1,20,0.0,0.000000,0.0,0.0,0.000000e+00,Syn
18029,6,61120524,10,2,60.0,6.0,6.0,0.0,6.0,6.0,...,0,5840,0,20,34.0,57.157677,100.0,1.0,6.986067e+06,Syn
15631,6,1,2,0,12.0,6.0,6.0,0.0,0.0,0.0,...,0,5840,-1,20,0.0,0.000000,0.0,0.0,0.000000e+00,Syn
15375,6,100,2,2,12.0,6.0,6.0,0.0,6.0,6.0,...,0,5840,0,20,0.0,0.000000,0.0,0.0,0.000000e+00,Syn
17535,6,49,2,0,12.0,6.0,6.0,0.0,0.0,0.0,...,0,5840,-1,20,0.0,0.000000,0.0,0.0,0.000000e+00,Syn
18771,6,52,2,2,12.0,6.0,6.0,0.0,6.0,6.0,...,0,5840,0,20,0.0,0.000000,0.0,0.0,0.000000e+00,Syn
18267,6,48,2,0,12.0,6.0,6.0,0.0,0.0,0.0,...,0,5840,-1,20,0.0,0.000000,0.0,0.0,0.000000e+00,Syn
17441,6,102,2,2,12.0,6.0,6.0,0.0,6.0,6.0,...,0,5840,0,20,0.0,0.000000,0.0,0.0,0.000000e+00,Syn

In [8]:
selected_columns = ['Protocol', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 
                    'Fwd Packets Length Total', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 
                    'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 
                    'Bwd Packet Length Mean', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 
                    'Flow IAT Max', 'Flow IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Min', 
                    'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 
                    'Bwd Header Length', 'Bwd Packets/s', 'Packet Length Max', 'FIN Flag Count', 'SYN Flag Count', 
                    'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 
                    'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 
                    'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Init Fwd Win Bytes', 'Init Bwd Win Bytes', 
                    'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Std', 'Label']

syn_df = pd.read_csv('temp/actual_data/test_syn.csv')
syn_df = syn_df[syn_df['Label'] == 'Syn']
syn_df = syn_df[selected_columns]

In [9]:
syn_df.sample(10)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,...,Bwd Avg Bulk Rate,Init Fwd Win Bytes,Init Bwd Win Bytes,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Std,Label
154,6,0.000000e+00,1,0,60,60.0,60.0,0.0,0.0,0.0,...,0.0,0,0,26,0.0,0.0,0.0,0.0,0.0,Syn
1478,6,0.000000e+00,1,0,60,60.0,60.0,0.0,0.0,0.0,...,0.0,0,0,26,0.0,0.0,0.0,0.0,0.0,Syn
1344,6,0.000000e+00,1,0,60,60.0,60.0,0.0,0.0,0.0,...,0.0,0,0,26,0.0,0.0,0.0,0.0,0.0,Syn
570,6,0.000000e+00,1,0,60,60.0,60.0,0.0,0.0,0.0,...,0.0,0,0,26,0.0,0.0,0.0,0.0,0.0,Syn
211,6,0.000000e+00,1,0,60,60.0,60.0,0.0,0.0,0.0,...,0.0,0,0,26,0.0,0.0,0.0,0.0,0.0,Syn
1034,6,0.000000e+00,1,0,60,60.0,60.0,0.0,0.0,0.0,...,0.0,0,0,26,0.0,0.0,0.0,0.0,0.0,Syn
935,6,0.000000e+00,1,0,60,60.0,60.0,0.0,0.0,0.0,...,0.0,0,0,26,0.0,0.0,0.0,0.0,0.0,Syn
60,6,0.000000e+00,1,0,60,60.0,60.0,0.0,0.0,0.0,...,0.0,0,0,26,0.0,0.0,0.0,0.0,0.0,Syn
1128,6,0.000000e+00,1,0,60,60.0,60.0,0.0,0.0,0.0,...,0.0,0,0,26,0.0,0.0,0.0,0.0,0.0,Syn
1179,6,3.401311e+07,2,0,120,60.0,60.0,0.0,0.0,0.0,...,0.0,512,0,26,0.0,0.0,0.0,0.0,0.0,Syn